services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.python
    working_dir: /app
    volumes:
      - ..:/app
    environment:
      - PYTHONPATH=/app
    env_file:
      - ../.env
    command: bash

  node:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    working_dir: /app
    volumes:
      - ..:/app
    env_file:
      - ../.env
    command: bash
